/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmail.romanrum45.Goods;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rum
 */
public class GoodsUI extends JFrame {

    private ListSelectionModel listSelectionModel;

    private ModelGoods modelGoods;
    private ChangeGoodsDialogGUI changeGoodsDialogGUI;
    private NotSelectedRowDialogGUI notSelectedRowDialogGUI;

    /**
     * Creates new form GoodsUI
     *
     * @param modelGoods
     */
    public GoodsUI(ModelGoods modelGoods) {

        this.modelGoods = modelGoods;

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoodsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoodsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoodsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoodsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        UIManager.put(
                "FileChooser.saveButtonText", "Сохранить");
        UIManager.put(
                "FileChooser.cancelButtonText", "Отмена");
        UIManager.put(
                "FileChooser.fileNameLabelText", "Наименование файла");
        UIManager.put(
                "FileChooser.filesOfTypeLabelText", "Типы файлов");
        UIManager.put(
                "FileChooser.lookInLabelText", "Директория");
        UIManager.put(
                "FileChooser.saveInLabelText", "Сохранить в директории");
        UIManager.put(
                "FileChooser.folderNameLabelText", "Путь директории");

        initComponents();
        changeSelectedRowListener();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextFieldCategory = new javax.swing.JTextField(30);
        jTextFieldName = new javax.swing.JTextField(30);
        jTextFieldDateRegistration = new javax.swing.JTextField(10);
        jTextFieldCost = new javax.swing.JTextField(10);
        jTextFieldQuantity = new javax.swing.JTextField(10);
        jTextFieldConsignmentNumber = new javax.swing.JTextField(20);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonCreateGoods = new javax.swing.JButton();
        jButtonChangeGoods = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonSearchByCategory = new javax.swing.JButton();
        jTextFieldSearchData = new javax.swing.JTextField();
        jButtonSearchByNumber = new javax.swing.JButton();
        jLabelIncorrect = new javax.swing.JLabel();
        jButtonCalculateSum = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Goods");

        jTextFieldCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCategoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Категория");

        jLabel2.setText("Название");

        jLabel3.setText("Дата оформления");

        jLabel4.setText("Цена за 1 ед.");

        jLabel5.setText("Количество");

        jLabel6.setText("Номер накладной");

        jButtonCreateGoods.setText("Создать товар");
        jButtonCreateGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateGoodsActionPerformed(evt);
            }
        });

        jButtonChangeGoods.setText("Изменить");
        jButtonChangeGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeGoodsActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Категория", "Название", "Дата оформления", "Цена за 1 ед.", "Количество", "Номер накладной"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Сортировать по", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButton1.setText("Цене");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Поиск по:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButtonSearchByCategory.setText("Категории");
        jButtonSearchByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchByCategoryActionPerformed(evt);
            }
        });

        jButtonSearchByNumber.setText("Накладной");
        jButtonSearchByNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchByNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSearchByCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSearchByNumber)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldSearchData, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jTextFieldSearchData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchByCategory)
                    .addComponent(jButtonSearchByNumber)))
        );

        jLabelIncorrect.setForeground(new java.awt.Color(255, 0, 0));
        jLabelIncorrect.setText("Неккоректные цифры");

        jButtonCalculateSum.setText("Посчитать стоимость");
        jButtonCalculateSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateSumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCalculateSum)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChangeGoods))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDateRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldQuantity))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldConsignmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIncorrect)
                                    .addComponent(jButtonCreateGoods)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDateRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConsignmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreateGoods))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonChangeGoods)
                            .addComponent(jButtonCalculateSum)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelIncorrect)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabelIncorrect.setVisible(false);

        jMenuFile.setText("Файл");

        jMenuItemOpen.setText("Открыть");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuItemSaveAs.setText("Сохранить как");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSaveAs);

        jMenuBar1.add(jMenuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCategoryActionPerformed

    private void jButtonCreateGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateGoodsActionPerformed
        String category = jTextFieldCategory.getText();
        String name = jTextFieldName.getText();
        String dateRegistration = jTextFieldDateRegistration.getText();
        int cost;
        int quantity;
        if (ModelGoods.isNumeric(jTextFieldCost.getText()) && ModelGoods.isNumeric(jTextFieldQuantity.getText())) {
            cost = Integer.valueOf(jTextFieldCost.getText());
            quantity = Integer.valueOf(jTextFieldQuantity.getText());
            jLabelIncorrect.setVisible(false);
        } else {
            jLabelIncorrect.setVisible(true);
            return;
        }
        String consignmentNumber = jTextFieldConsignmentNumber.getText();
        if (modelGoods.searchByConsignmentNumber(consignmentNumber) != null) {
            JOptionPane.showMessageDialog(this, "Товар с такой накладной уже существует.");
        } else {

            modelGoods.createGoods(category, name, dateRegistration, cost, quantity, consignmentNumber);
            jTextFieldCategory.setText("");
            jTextFieldName.setText("");
            jTextFieldDateRegistration.setText("");
            jTextFieldCost.setText("");
            jTextFieldQuantity.setText("");
            jTextFieldConsignmentNumber.setText("");

            updateTable();
        }
    }//GEN-LAST:event_jButtonCreateGoodsActionPerformed

    private void jButtonChangeGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeGoodsActionPerformed
        if (modelGoods.getTableSelectedRow() != -1) {
            changeGoodsDialogGUI = new ChangeGoodsDialogGUI(modelGoods, this);
            changeGoodsDialogGUI.setVisible(true);
        } else {
            notSelectedRowDialogGUI = new NotSelectedRowDialogGUI();
            notSelectedRowDialogGUI.setVisible(true);
        }
    }//GEN-LAST:event_jButtonChangeGoodsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listenerSort();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSearchByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchByCategoryActionPerformed
        String searchData = jTextFieldSearchData.getText();
        Goods foundGoods = null;
        foundGoods = modelGoods.searchByCategory(searchData);
        outputFoundGoods(foundGoods);
    }//GEN-LAST:event_jButtonSearchByCategoryActionPerformed

    private void jButtonSearchByNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchByNumberActionPerformed
        String searchData = jTextFieldSearchData.getText();
        Goods foundGoods = null;
        foundGoods = modelGoods.searchByConsignmentNumber(searchData);
        outputFoundGoods(foundGoods);
    }//GEN-LAST:event_jButtonSearchByNumberActionPerformed

    private void jButtonCalculateSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateSumActionPerformed
        if (modelGoods.getTableSelectedRow() != -1) {
            int numSelectedRow = modelGoods.getTableSelectedRow();
            String sumGoods = String.valueOf(modelGoods.getGoods()[numSelectedRow].calculateSum());
            SumGoodsDialogGUI sumGoodsDialogGUI = new SumGoodsDialogGUI(sumGoods);
            sumGoodsDialogGUI.setVisible(true);

        } else {
            notSelectedRowDialogGUI = new NotSelectedRowDialogGUI();
            notSelectedRowDialogGUI.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCalculateSumActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed

        JFileChooser fileopen = new JFileChooser();
        String nameFile;
        int ret = fileopen.showDialog(null, "Открыть файл");
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileopen.getSelectedFile();
            String stateOpen = modelGoods.openFileTxt(file);
            updateTable();
            JOptionPane.showMessageDialog(this, stateOpen);
            //controller.setPath(nameFile);  
        }
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed

        if (modelGoods.getTableSelectedRow() != -1) {
            JFileChooser fileSave = new JFileChooser();
            String nameFile;
            int ret = fileSave.showDialog(null, "Сохранить файл");
            if (ret == JFileChooser.APPROVE_OPTION) {
                modelGoods.saveInFileTxt(fileSave.getSelectedFile());
                JOptionPane.showMessageDialog(this,
                        "Файл '" + fileSave.getSelectedFile()
                        + " ' сохранен");
                //fileSave.get
                //nameFile = file.getAbsolutePath();     
                //controller.setPath(nameFile);  
            }
        } else {
            JOptionPane.showMessageDialog(this, "Не выбрана строка таблицы.");
        }
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void outputFoundGoods(Goods foundGoods) {
        if (foundGoods != null) {
            Object[] arrValues = foundGoods.getValuesGood();
            Object[][] twoArray = new Object[1][ModelGoods.COLUMNS.length];
            twoArray[0] = arrValues;
            jTable1.setModel(new DefaultTableModel(twoArray, ModelGoods.COLUMNS));
        } else {
            jTable1.setModel(new DefaultTableModel(new Object[][]{}, ModelGoods.COLUMNS));
            NotFoundDialogGUI notFoundDialogGUI = new NotFoundDialogGUI();
            notFoundDialogGUI.setVisible(true);
        }
    }

    private void changeSelectedRowListener() {
        listSelectionModel = jTable1.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listSelectionModel.addListSelectionListener((ListSelectionEvent e) -> {
            if (e.getValueIsAdjusting() == true) {
                modelGoods.setTableSelectedRow(jTable1.getSelectedRow());
            }
        });
        
    }

    // Обновляем таблицу
    public void updateTable() {
        Goods[] arGoods = modelGoods.getGoods();
        Object[][] twoArray = new Object[arGoods.length][ModelGoods.COLUMNS.length];
        for (int i = 0; i < arGoods.length; i++) {
            twoArray[i] = arGoods[i].getValuesGood();

        }
        jTable1.setModel(new DefaultTableModel(twoArray, ModelGoods.COLUMNS) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        //RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        //jTable1.setRowSorter(sorter);
    }

    public void listenerSort() {
        modelGoods.sortByCost();
        updateTable();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCalculateSum;
    private javax.swing.JButton jButtonChangeGoods;
    private javax.swing.JButton jButtonCreateGoods;
    private javax.swing.JButton jButtonSearchByCategory;
    private javax.swing.JButton jButtonSearchByNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelIncorrect;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCategory;
    private javax.swing.JTextField jTextFieldConsignmentNumber;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldDateRegistration;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldSearchData;
    // End of variables declaration//GEN-END:variables
}
