/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmail.romanrum45.Goods;

import javax.swing.JDialog;

/**
 *
 * @author Rum
 */
public class SumGoodsDialogGUI extends JDialog {    
    

    /**
     * Creates new form SumGoodsDialogGUI
     */
    public SumGoodsDialogGUI(String sumGoods) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        jLabelSumGoods.setText("Стоимость товара = " + sumGoods);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSumGoods = new javax.swing.JLabel();
        jButtonОк = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Стоимость товара");

        jLabelSumGoods.setText("Стоимость товара =");

        jButtonОк.setText("Ок");
        jButtonОк.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonОкActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButtonОк))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelSumGoods)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelSumGoods)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonОк)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonОкActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonОкActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonОкActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonОк;
    private javax.swing.JLabel jLabelSumGoods;
    // End of variables declaration//GEN-END:variables
}
